### ISSUE TITLE
Build against a given User-Agent/browserlist string?

### ISSUE THREAD

**Issue by oncletom** [Financial-Times/polyfill-service-url-builder#10]
Hello,

I was wondering if there was a plan to add a "browser" option, so as the generated URI is built against a minimum browser version.

I'd like to factor the URI for a given browser (ex: Firefox ESR), instead of having a fully complete set of features listed in the URI (I assume I won't support some deprecated browsers).

```bash
# currently I do
$ npx create-polyfill-service-url analyse --file build/bundle.js

# what I wish I could do
$ npx create-polyfill-service-url analyse --file build/bundle.js --browser "firefox-esr"

# dreamlike
$ npx create-polyfill-service-url analyse --file build/bundle.js --browser "firefox-esr,edge,last 2 version,> 10% in FR"
```

Thank you for your time!

**Comment by JakeChampion** [comment]
Hey @oncletom, long time no see/speak! I remember working with you in BBC World Service on a Grunt task to automate the internalization of the labels on the website when I was an intern there, I hope you are doing well :-)

Your feature request is a great idea, I've made a pull-request for it #14

**Comment by oncletom** [comment]
Oh hi @JakeChampion 🙂 

It's super nice from you to have taken the time to follow up on this.
Keep up the good work!

**Comment by adamjohnson** [comment]
Having some trouble with this feature. Here's what I ran:

```
npx create-polyfill-service-url analyse --file baguetteBox.min.js --browser "IE 11"
```

Tested my browser string on [browserlist.dev](https://browserslist.dev/). After running the command, I get `Unknown argument: browser` and `browser` is not listed in `Options` after running `--help`.

[Full output](https://pastebin.com/Tsr8eMg7) if you're curious. 

__________________________________________________________________

This is a great feature to have! 👏   for working on it.
