### ISSUE TITLE
The url missing some features.

### ISSUE THREAD

**Issue by Awen-hub** [Financial-Times/polyfill-service-url-builder#265]
## What

I have got a fault when I use the tool to create a url.

## Details

My file content is (myfile.js): 
`
! function () {
  "use strict";
  var t = function (t, r) {
    var e = document.getElementById("test-table"),
      n = r(),
      s = n.status,
      o = n.message;
    /native code/.test(o) && (o = "浏览器已支持此API，请用更低版本浏览器进行测试");
    try {
      e.innerHTML += !1 === s ? "<th>" + t + "</th><th style='background: red'>ㄨ</th><th>" + o + "</th>" : "<th>" + t + "</th><th>✓</th><th>" + o + "</th>"
    } catch (r) {
      console.error(r), e.innerHTML += "<th>" + t + "</th><th style='background: red'>ㄨ</th><th>" + o + "</th><th>" + r + "</th>"
    }
  };
  t("Array.isArray", (function () {
    return {
      status: Array.isArray([]) && !Array.isArray({}),
      message: Array.isArray.toString()
    }
  })), t("Array.of", (function () {
    return {
      status: 7 === Array.of(7)[0],
      message: Array.of.toString()
    }
  })), t("Array.from", (function () {
    return {
      status: "f" === Array.from("foo")[0],
      message: Array.from.toString()
    }
  })), t("Array.prototype.includes", (function () {
    return {
      status: ![1].includes(0) && [0].includes[0],
      message: [].includes.toString()
    }
  })), t("Array.prototype.every", (function () {
    return {
      status: [1, 30, 39, 29, 10, 13].every((function (t) {
        return t < 40
      })),
      message: [].every.toString()
    }
  })), t("Array.prototype.every", (function () {
    return {
      status: 0 === [1, 2, 3, 4].fill(0, 2, 4)[2],
      message: [].fill.toString()
    }
  })), t("Array.prototype.forEach", (function () {
    var t = [5, 4, 5];
    return t.forEach((function (t, r, e) {
      e[r] = 1
    })), {
      status: 1 === t[0],
      message: [].forEach.toString()
    }
  })), t("Array.prototype.indexOf", (function () {
    var t = [2, 5, 9];
    return {
      status: 0 === t.indexOf(2) && -1 === t.indexOf(7),
      message: [].indexOf.toString()
    }
  })), t("Array.prototype.lastIndexOf", (function () {
    var t = ["Dodo", "Tiger", "Penguin", "Dodo"];
    return {
      status: 3 === t.lastIndexOf("Dodo") && -1 === t.lastIndexOf("a"),
      message: [].lastIndexOf.toString()
    }
  })), t("Array.prototype.reduce", (function () {
    return {
      status: 10 === [1, 2, 3, 4].reduce((function (t, r) {
        return t + r
      })),
      message: [].reduce.toString()
    }
  })), t("Array.prototype.reduceRight", (function () {
    return {
      status: 10 === [1, 2, 3, 4].reduceRight((function (t, r) {
        return t + r
      })),
      message: [].reduceRight.toString()
    }
  })), t("Array.prototype.some", (function () {
    return {
      status: !0 === [1, 2, 3, 4, 5].some((function (t) {
        return t % 2 == 0
      })),
      message: [].some.toString()
    }
  })), t("Array.prototype.filter", (function () {
    return {
      status: 130 === [12, 5, 8, 130, 44].filter((function (t) {
        return t >= 10
      }))[1],
      message: [].filter.toString()
    }
  })), t("Array.prototype.map", (function () {
    return {
      status: 2 === [1, 4, 9, 16].map((function (t) {
        return 2 * t
      }))[0],
      message: [].map.toString()
    }
  })), t("String.prototype.trim", (function () {
    return {
      status: "abc" === " abc".trim(),
      message: "".trim.toString()
    }
  })), t("String.prototype.endsWith", (function () {
    return {
      status: !1 === "Cats are the best!".endsWith("?"),
      message: "".endsWith.toString()
    }
  })), t("String.prototype.includes", (function () {
    return {
      status: !1 === " abc".includes("d"),
      message: "".includes.toString()
    }
  })), t("String.prototype.startsWith", (function () {
    return {
      status: !1 === " abc".startsWith("D"),
      message: "".startsWith.toString()
    }
  }))
}();
`
Run "create-polyfill-service-url analyse --file myfile.js"  and then I get the url "https://polyfill.io/v3/polyfill.min.js?features=Array.from,Array.of,Array.prototype.fill,Array.prototype.includes,console,document,Map,modernizr:es5array,Set,String.prototype.endsWith,String.prototype.includes,String.prototype.startsWith,String.prototype.trim,Symbol". However, lots of features are missing, such as "Array.prototype.forEach", "Array.prototype.some" and "Array.prototype.every". Is it a bug?

**Comment by JakeChampion** [comment]
Hi @Awen-hub, the array methods you mentioned are all included within the group alias ["modernizr:es5array"](https://github.com/Financial-Times/polyfill-library/search?q=modernizr%3Aes5array) that is in the generated url

Were they the only features that were missing?

**Comment by Awen-hub** [comment]
> Hi @Awen-hub, the array methods you mentioned are all included within the group alias ["modernizr:es5array"](https://github.com/Financial-Times/polyfill-library/search?q=modernizr%3Aes5array) that is in the generated url
> 
> Were they the only features that were missing?

Yes. Thanks for your answer.
