### ISSUE TITLE
Programmatic usage

### ISSUE THREAD

**Issue by antony** [Financial-Times/polyfill-service-url-builder#41]
I have an idea for a rollup plugin based around this, but it's a bit awkward right now as the project doesn't have a non-cli API I can use to do so.

Is there any interest in pushing the abstraction down into a further layer, so that it can be called from other JS code without having to shell out or `exec`?

**Comment by JakeChampion** [comment]
This is a feature we won't be implementing as we do not require it.

If you want to implement this feature then we will be happy to review the pull-request and look at merging it in 👍
